import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Container, Grid, Text, Title } from "@mantine/core";
import { Carousel } from "@mantine/carousel";
import HeaderComponent from "../components/header";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
        <Container my={40} py={40}>
              <Title>Admin Panel</Title>
          <Grid>
            <Grid.Col span={6}>
            </Grid.Col>
            <Grid.Col span={6}>
            </Grid.Col>
          </Grid>
        </Container>
      </main>

      <footer></footer>
    </div>
  );
}
