import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box, Button, Container, Grid, Text, Title } from "@mantine/core";
import { Carousel } from "@mantine/carousel";
import HeaderComponent from "../components/header";
import Cardslider from "../components/cardslider";
import Book from "../components/book";
import resort1 from "../assets/resort1.jpg";
import resort2 from "../assets/resort2.jpg";
import resort3 from "../assets/resort3.jpg";
import resort4 from "../assets/resort4.jpg";
import { mrDafoe } from "../styles/themes/typography";
import FeaturesGrid from "../components/features";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container mb={40} size="lg" fluid p={0}>
          <Carousel
            mx="auto"
            withIndicators
            height={"90vh"}
            loop
            withControls={false}
          >
            <Carousel.Slide
              style={{
                background: `url(${resort4.src}) no-repeat fixed center`,
                backgroundSize: "cover",
                boxShadow: "inset 0 0 0 2000px #00000040",
              }}
            >
              <Container mt={100} mb={30} size="lg">
                <Grid>
                  <Grid.Col span={12} xs={8}>
                    <Text weight={100} px={6} color="#fff">
                      WELCOME TO
                    </Text>
                    <Title
                      px={10}
                      weight={300}
                      color="#fff"
                      style={{
                        lineHeight: "84px",
                        fontFamily: mrDafoe.style.fontFamily,
                        fontSize: "clamp(4rem, -1.5rem + 18vw, 6rem)",
                      }}
                    >
                      Fairmount
                    </Title>
                    <Text weight={100} px={6} mb={20} color="#fff">
                      RESORTS, WAGAMON
                    </Text>
                    <Text weight={100} px={6} mb={10} color="#fff" size={13}>
                      One of the most popular FairMount Vagamon Resort, offers a
                      perfect blend of all modern luxuries and a comfortable
                      companionship of nature. we have provided premium resort
                      experience and a comfortable companionship of nature. we
                      have provided premium resort experience
                    </Text>
                    <Box px={6}>
                    <Button variant="white" color="dark" size={'xs'}>
                      Read article
                    </Button></Box>
                  </Grid.Col>
                </Grid>
              </Container>
            </Carousel.Slide>
            <Carousel.Slide
              style={{
                background: `url(${resort2.src}) no-repeat fixed center`,
                backgroundSize: "cover",
                boxShadow: "inset 0 0 0 2000px #00000040",
              }}
            >
              <Container mt={100} mb={30} size="lg">
                <Grid>
                  <Grid.Col span={12} xs={8}>
                    <Text weight={100} px={6} color="#fff">
                      WELCOME TO
                    </Text>
                    <Title
                      px={10}
                      weight={300}
                      color="#fff"
                      style={{
                        lineHeight: "84px",
                        fontFamily: mrDafoe.style.fontFamily,
                        fontSize: "clamp(4rem, -1.5rem + 18vw, 6rem)",
                      }}
                    >
                      Fairmount
                    </Title>
                    <Text weight={100} px={6} mb={20} color="#fff">
                      RESORTS, WAGAMON
                    </Text>
                    <Text weight={100} px={6} mb={10} color="#fff" size={13}>
                      One of the most popular FairMount Vagamon Resort, offers a
                      perfect blend of all modern luxuries and a comfortable
                      companionship of nature. we have provided premium resort
                      experience and a comfortable companionship of nature. we
                      have provided premium resort experience
                    </Text>
                    <Box px={6}>
                    <Button variant="white" color="dark" size={'xs'}>
                      Read article
                    </Button></Box>
                  </Grid.Col>
                </Grid>
              </Container>
            </Carousel.Slide>
            <Carousel.Slide
              style={{
                background: `url(${resort3.src}) no-repeat fixed center`,
                backgroundSize: "cover",
                boxShadow: "inset 0 0 0 2000px #00000040",
              }}
            >
              <Container mt={100} mb={30} size="lg">
                <Grid>
                  <Grid.Col span={12} xs={8}>
                    <Text weight={100} px={6} color="#fff">
                      WELCOME TO
                    </Text>
                    <Title
                      px={10}
                      weight={300}
                      color="#fff"
                      style={{
                        lineHeight: "84px",
                        fontFamily: mrDafoe.style.fontFamily,
                        fontSize: "clamp(4rem, -1.5rem + 18vw, 6rem)",
                      }}
                    >
                      Fairmount
                    </Title>
                    <Text weight={100} px={6} mb={20} color="#fff">
                      RESORTS, WAGAMON
                    </Text>
                    <Text weight={100} px={6} mb={10} color="#fff" size={13}>
                      One of the most popular FairMount Vagamon Resort, offers a
                      perfect blend of all modern luxuries and a comfortable
                      companionship of nature. we have provided premium resort
                      experience and a comfortable companionship of nature. we
                      have provided premium resort experience
                    </Text>
                    <Box px={6}>
                    <Button variant="white" color="dark" size={'xs'}>
                      Read article
                    </Button></Box>
                  </Grid.Col>
                </Grid>
              </Container>
            </Carousel.Slide>
            {/* ...other slides */}
          </Carousel>
        </Container>
        <Container mt={30} mb={60} size="lg">
          <Title
            weight={300}
            size={"10vw"}
            style={{
              lineHeight: "124px",
              textAlign: "center",
              fontFamily: mrDafoe.style.fontFamily,
              fontSize: "clamp(4rem, -1.5rem + 18vw, 8rem)",
            }}
          >
            Fairmount
          </Title>
          <Text
            style={{
              textAlign: "center",
            }}
          >
            VAGAMON
          </Text>
        </Container>
        <Container mt={30} mb={30} size="lg">
          <Grid align="center">
            <Grid.Col span={12} xs={6}>
              <Title weight={100} order={2}>
                Fairmount Resort Vagamon
              </Title>
            </Grid.Col>
            <Grid.Col span={12} xs={6}>
              <Text size={13}>
                One of the most popular{" "}
                <strong>FairMount Vagamon Resort</strong>, offers a perfect
                blend of all modern luxuries and a comfortable companionship of
                nature. we have provided premium resort experience and a
                comfortable companionship of nature. we have provided premium
                resort experience.
              </Text>
            </Grid.Col>
          </Grid>
        </Container>
        <Container mt={30} mb={70} size="lg">
          <Image
            style={{
              borderRadius: 20,
            }}
            src={resort1}
            alt="Picture of the author"
            layout="responsive"
          />
        </Container>
        <Container
          mt={30}
          mb={30}
          py={80}
          fluid
          style={{ background: "#00000010" }}
        >
          <Container size={"lg"}>
            <Text style={{}}>FEATURES IN</Text>
            <Title weight={100} order={2} mb={30}>
              Fairmount Resort, Vagamon
            </Title>
            <Cardslider />
          </Container>
        </Container>
        <FeaturesGrid
          title={"This dust is actually"}
          description={
            "People say it can run at the same speed as lightning striking, Its icy body is so cold, it will not melt even if it is immersed in magma.This dust is actually a powerful poison that will even make a pro wrestler sick, Regice cloaks itself with frigid air of -328 degrees Fahrenheit"
          }
        />
        <Container py={20} size="lg">
                <div
                  dangerouslySetInnerHTML={{
                    __html:
                      '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3933.0738354558407!2d76.90342611432996!3d9.67473258120565!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3b07b4976ea12685%3A0x7695e1e5cc9b13e5!2sFairmount%20Vagamon%20Resorts!5e0!3m2!1sen!2sin!4v1670861868831!5m2!1sen!2sin" style="width:100%;border:none;" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
                  }}
                />
              </Container>
      </main>

      <footer></footer>
    </div>
  );
}
